name: Release

on:
  push:
    branches:
      - master
      - 2020.3
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: release
        run: sbt ci-release
